name: Build and Push PHP Base Image

on:
  push:
    branches:
      - main
    paths:
      - 'images/php/84-fpm-alpine312/prod.Dockerfile'
      - 'images/php/84-fpm-alpine312/Dockerfile'
      - 'images/php/84-fpm-alpine312/config/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: images/php/84-fpm-alpine312
          file: images/php/84-fpm-alpine312/prod.Dockerfile
          push: true
          tags: tomaskrcal99/php:8.4-fpm-alpine3.21

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: images/php/84-fpm-alpine312
          file: images/php/84-fpm-alpine312/Dockerfile
          push: true
          tags: tomaskrcal99/php:8.4-fpm-alpine3.21-dev
